# -*- coding: utf-8 -*-
"""D1 Git/Github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ycqz2Jq3H2Op7tccHzP3txhViaCDqLdT
"""

import json

from dataclasses import replace
f = open('farmers-protest-tweets-2021-03-5.json', 'r')
data = []
numb = 0
for line in f.readlines():
  print(numb)
  print(type(line))
  # z = json.dumps(line)
  # print(type(z))
  json_object = json.loads(line)
  print(type(json_object))
  numb += 1
  data.append(json.dumps(line))

print(type(data[1]))

